db/db_store.go, db/db_wrapper.go, db/settings.go, go.mod, go.sum
=> DB wrapper code

vin_utils.go, vin_utils_test.go
=> Support vin decode years 2005-2034

api/devices/user_devices.proto
New GRPC Endpoint to return User Device by AutoPIUnitID
=> GetUserDeviceByAutoPIUnitId added

vin_utils.go, vin_utils_test.go
=> PLA-597 - VDS, VIS, CheckDigit, SerialNumber Added

middleware/privilegetoken/main_test.go
=> Unit tests for privilege middleware

odometer_utils.go
- we had this same thing in 2 possibly 3 repos so better to centralize, specially if we need to change it over time
=> is odo valid logic

odometer_utils.go
=> PRO-1595 additional odo check filter

grpc_utils.go
=> PRO-1623 grpc to fiber err

internal/appmetrics/counter.go
=> edit counter.go

grpc_utils.go
=> if can't convert error to grpc error, just return err

privileges/privileges.go
Adds Privileges package and enum. This code alone may not warrant its package, but things can get out of hand if we keep everything flat. If reviewers disagree, I do not mind moving the location.
=> Adds privileges package and enum.

privileges/privileges.go
=> add vin vc priv

go.mod, http_client_wrapper.go, http_client_wrapper_test.go
=> Add Retry Dinamic

sdtask/sdtask.go
=> Put the credential data definitions in a central place for now

device/models.go
=> add shared config response

set/set.go, set/set_test.go
=> Range over set. Not clear if this is useful to anyone

privileges/privileges.go
Update permissions to match 
https://github.com/DIMO-Network/web3-deploys/blob/main/Polygon/PolygonDeploys.md
=> Add constants for new perms

pkg/http/http_client_wrapper.go, pkg/http/http_client_wrapper_test.go
=> INTG-1715 Add a graphql query helper to our existing http client wrapper

pkg/vin/vin_utils.go, pkg/vin/vin_utils_test.go
=> support japan chassis number

pkg/vin/vin_utils_test.go
wanted to see how this behaved in invalid case scenario
=> add unit test for tesla

pkg/cryptoutils/crypto.go
=> package rename to make more sense

pkg/vin/vin_utils.go, pkg/vin/vin_utils_test.go
- update naming for vin validation functions
- update japan chassis validation to use regex, update tests
- add is vin valid function
=> add vin validation func, updates to japan chassis validation
